name: Build plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GeyserUpdater
        path: |
          target/*.jar
          !target/original-*.jar